url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "United Against COVID-19"
collections:
    - platforms
    - initiatives